---
name: Backport merged pull request

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [closed, labeled]

jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - name: Get Github App Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Clone Firmware
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Token for git actions, e.g. git push
          token: ${{ steps.app-token.outputs.token }}

      - name: Create backport pull requests
        uses: korthout/backport-action@c656f5d5851037b2b38fb5db2691a03fa229e3b2 # v4.0.1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          auto_merge_enabled: true
          experimental: >
            {
              "conflict_resolution": "draft_commit_conflicts"
            }
