---
name: "Update Targets"

on:
  workflow_dispatch:
  push:
    branches:
      - 'gluon-*'  # gluon-next and gluon-v202a.1.x
    paths:
      - 'Makefile'

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  update-Modules:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Firmware
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get Github App Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Get update branch name
        id: branch-name
        run: echo "branch-name=update-targets-${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Run update-targets
        run: make update-targets

      - name: Get new targets
        id: new-targets
        run:
          echo "names=$(git diff --color=always|perl -wlne 'print $1 if /^\e\[32m\+\e\[m\e\[32m(.*)\e\[m$/' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: '[${{ github.ref_name }}] Add targets ${{ steps.new-targets.outputs.names }}'
          body: |
            Updated targets for branch ${{ github.ref_name }}

            New targets: `${{ steps.new-targets.outputs.names }}`
          commit-message: "targets: add ${{ steps.new-targets.outputs.names }}"
          committer: ${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>
          branch: ${{ steps.branch-name.outputs.branch-name }}
          labels: ${{ github.ref_name }}
          delete-branch: true

      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
