---
name: "Update Targets"

on:
  workflow_dispatch:
  push:
    branches:
      - 'gluon-*'  # gluon-next and gluon-v202a.1.x
    paths:
      - 'Makefile'

permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests

jobs:
  update-Modules:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Firmware
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Get Github App Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Get update branch name
        id: branch-name
        run: echo "branch-name=update-targets-${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Run update-targets
        run: make update-targets

      - name: Get new targets
        id: new-targets
        run:
          echo "names=$(git diff --color=always|perl -wlne 'print $1 if /^\e\[32m\+\e\[m\e\[32m(.*)\e\[m$/' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: '[${{ github.ref_name }}] Add targets ${{ steps.new-targets.outputs.names }}'
          body: |
            Updated targets for branch ${{ github.ref_name }}

            New targets: `${{ steps.new-targets.outputs.names }}`
          commit-message: "targets: add ${{ steps.new-targets.outputs.names }}"
          committer: ${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>
          branch: ${{ steps.branch-name.outputs.branch-name }}
          labels: ${{ github.ref_name }}
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --auto "1"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
